project:
  type: website
  output-dir: docs

website:
  title: "Miheer Dewaskar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research-overview.qmd
        text: My research
      - href: research-papers.qmd
        text: Papers
      - teaching.qmd
      - talks.qmd
      - href: more.qmd
        text: More
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



