---
title: "Service & Awards"
---

## Journals refereed

- [Bayesian Analysis](https://projecteuclid.org/journals/bayesian-analysis) (1)
- [Biometrika](https://academic.oup.com/biomet/) (1)
- [Journal of the American Statistical Association](https://www.tandfonline.com/journals/uasa20) (1)
- [Journal of Applied Statistics](https://www.tandfonline.com/journals/cjas20) (1)
- [Mathematics of Operations Research](https://pubsonline.informs.org/journal/moor) (2)
- [Proceedings of the American Mathematical Society](https://pubs.ams.org/journals/proc) (1)
- [Stochastic Processes and their Applications](https://www.sciencedirect.com/journal/stochastic-processes-and-their-applications) (1)


## Awards during education

- **Cambanis-Hoeffding-Nicholson award (2017)** by Department of Statistics and Operations Research at UNC Chapel Hill for top performance in the qualifying exam.
- **Medal of Excellence (2016)** by Chennai Mathematical Institute for top performance in M.Sc. Computer Science.
- **Charpak Scholarship (2015)** by French Embassy to pursue a research internship with    [Team SUMO](https://www.irisa.fr/sumo/).
- **INSPIRE Scholarship (2011-14)** by Department of Science and Technology in India to pursue an education in the basic sciences.